class SlidingWindow:
    def __init__(self, capacity: int, period: float) -> None: ...
    def get_tokens(self, current: float | None) -> float: ...
    def get_retry_after(self) -> float: ...
    def update_ratelimit(self) -> float | None: ...
